### ISSUE TITLE
v1.5.0 is not backward compatible

### ISSUE THREAD

**Issue by pacoorozco** [int128/oauth2cli#3]
Hi @int128 
I've noticed that v1.5.0 is not backwards compatible. I was using your beautiful code in my project and it started to fail due to the `ShowLocalServerURL` deprecation. 
Due to this change a major version should be publish, what do you think? 
Thanks very much for your useful project

**Comment by int128** [comment]
Exactly v1.5.0 has breaking changes and should be a major release as semantic versioning. Sorry for confusing. I added migration ways to https://github.com/int128/oauth2cli/releases/tag/v1.5.0.

**Comment by pacoorozco** [comment]
Thanks @int128 I was already migrated to the new version, but I don't know if other people is using the same... you can remove tag v1.5.0 and publish the major one v2.0.0 :sweat: 

But feel free to close this issue
