### ISSUE TITLE
Allow listener to listen to all interfaces

### ISSUE THREAD

**Issue by pacoorozco** [int128/oauth2cli#4]
If you try to run `oauth2cli` inside a docker, you are not going to be able to reach `http://localhost:port` (even though you expose and map the port). The problem is that the listener is only configured for `localhost`.

Can you enable a config option to listen to all interfaces?

I can help with a PR if you agrees.

**Comment by pacoorozco** [comment]
Created PR #5 , feel free to use it or not @int128

**Comment by int128** [comment]
I just created PR #7. Would you take a look?

**Comment by int128** [comment]
Would you try the new release https://github.com/int128/oauth2cli/releases/tag/v1.6.0 ?
Thank you for the contribution.

**Comment by pacoorozco** [comment]
I've test it,,, it's working right... Thanks a lot @int128
